### ISSUE TITLE
Original Language Of Keter 

### ISSUE THREAD

**Issue by loralighte** [Random-People/KETER#1]
We must ask this because we need to choose what language compiles Keter. Reply with suggestions. Once all languages have been selected I will make a vote system to choose the language.

- Golang
- C / C++
- Crystal

**Comment by loralighte** [comment]
If there is any confusion please ask to clarify whatever

**Comment by ghost** [comment]
@KaiLikesLinux I guess you should use C / C++ to compile Keter.

**Comment by loralighte** [comment]
I guess it is decided
